Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CsharpHome.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CsharpHome.Controllers
{
    public class LoginController : Controller
    {
        private string userFromPair = "";
        private int attemptFromPair  = 0;
        Dictionary<string, int> usersAttemptsList = new Dictionary<string, int>();
        List<string> userAttemptsPair = new List<string>();

        // GET: Login
        public ActionResult Index()
        {
            //Response.Cookies.Add(CreateUserCookie());
            //if (Request.Cookies["UserCookie"] == null)

            /*
             idea: set User as cookie name; Attemps as its value
             */

                Response.Cookies.Add(CreateUserCookie());
            return View();
        }

        [HttpPost]
        public ActionResult Index(string username, string password)
        {
            ViewBag.LoginUsername = username;
            ViewBag.LoginPassword = password;
            ViewBag.LoginRejected = false;            

            if (Session["UsersAttemps"] != null)
            {
                userAttemptsPair = Session["UsersAttemps"].ToString().Split(';').ToList();
                userAttemptsPair.RemoveAll(item => String.IsNullOrEmpty(item));
                foreach (var item in userAttemptsPair)
                {
                    userFromPair = item.Split(',')[0];
                    attemptFromPair = Int32.Parse(item.Split(',')[1]);

                    if (!usersAttemptsList.Keys.Contains(userFromPair))
                        usersAttemptsList.Add(userFromPair, attemptFromPair);
                    else if (usersAttemptsList[userFromPair] < attemptFromPair)
                        usersAttemptsList[userFromPair] = attemptFromPair;
                }
            }

            if (usersAttemptsList.Keys.Contains(username))
                usersAttemptsList[username] = usersAttemptsList[username] + 1;
            else
                usersAttemptsList.Add(username, 0);

            if (usersAttemptsList[username] == 3)
            {
                usersAttemptsList[username] = 0;
                ViewBag.LoginRejected = true;
            }
            else {
                ViewBag.LoginRejected = false;
            }

            foreach (var item in usersAttemptsList)
                Session["UsersAttemps"] = Session["UsersAttemps"] + ";" + item.Key + "," + item.Value;

            return View();
        }
        
        private HttpCookie CreateUserCookie()
        {
            HttpCookie UserCookies = Request.Cookies["UserCookie"];
            UserCookies = new HttpCookie("UserCookie");
            UserCookies.Value = Guid.NewGuid().ToString();
            Session["loginCount"] = 0;
            return UserCookies;
        }
        
    }
}

Controllers/ReverseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CsharpHome.Controllers
{
    public class ReverseController : Controller
    {
        // GET: Counter
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string letters)
        {
            ViewBag.ReversedLetters = letters.Reverse();
            return View();
        }
    }
}

Controllers/SpeedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CsharpHome.Controllers
{
    public class SpeedController : Controller
    {
        // GET: Speed
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(double distance, double time)
        {
            ViewBag.SpeedDistance = distance;
            ViewBag.SpeedTime = time;
            ViewBag.SpeedKmph = distance / time;
            ViewBag.SpeedMph = ViewBag.SpeedKmph * 0.621371;

            return View();
        }
    }
}

Controllers/TreeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CsharpHome.Controllers
{
    public class TreeController : Controller
    {
        // GET: Tree
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(int number, int width)
        {
            ViewBag.TreeNumber = number;
            ViewBag.TreeWidth = width;
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "List of tasks";
}

<div class="row">
    <div class="col-md-12">
        <h2>List of tasks:</h2>
        <div class="col-md-12 tasks">
            <h4>Task 1</h4>
            <p>Write a C# Sharp program that takes three letters as input and display them in reverse order.</p>
            <p>@Html.ActionLink("See solution", "Index", "Reverse")</p>
        </div>
        <div class="col-md-12 tasks">
            <h4>Task 2</h4>
            <p>Write a C# Sharp program that takes a number and a width also a number,as input and then displays a triangle of that width, using that number.</p>
            <p>@Html.ActionLink("See solution", "Index", "Tree")</p>
        </div>
        <div class="col-md-12 tasks">
            <h4>Task 3</h4>
            <p>Write a C# Sharp program that takes userid and password as input (type string). After 3 wrong attempts, user will be rejected.</p>
            <p>@Html.ActionLink("See solution", "Index", "Login")</p>
        </div>
        <div class="col-md-12 tasks">
            <h4>Task 4</h4>
            <p>Write a C# Sharp program that takes two numbers as input and perform an operation (+,-,*,x,/) on them and displays the result of that operation.</p>
            <p>@Html.ActionLink("See solution", "Index", "Calculator")</p>
        </div>
        <div class="col-md-12 tasks">
            <h4>Task 5</h4>
            <p>Write a C# Sharp program that takes the radius of a circle as input and calculate the perimeter and area of the circle.</p>
            <p>@Html.ActionLink("See solution", "Index", "CirclePerimeter")</p>
        </div>
        <div class="col-md-12 tasks">
            <h4>Task 6</h4>
            <p>Write a C# Sharp program to display certain values of the function x = y <sup>2</sup>  + 2 * y + 1 (using integer numbers for y , ranging from -5 to +5).</p>
            <p>@Html.ActionLink("See solution", "Index", "Function")</p>
        </div>
        <div class="col-md-12 tasks">
            <h4>Task 7</h4>
            <p>Write a C# Sharp program that takes distance and time as input and displays the speed in kilometers per hour and miles per hour.</p>
            <p>@Html.ActionLink("See solution", "Index", "Speed")</p>
        </div>
        <div class="col-md-12 tasks">
            <h4>Task 8</h4>
            <p>Write a C# Sharp program that takes the radius of a sphere as input and calculate and display the surface and volume of the sphere.</p>
            <p>@Html.ActionLink("See solution", "Index", "SphereVolume")</p>
        </div>
        <div class="col-md-12 tasks">
            <h4>Task 9</h4>
            <p>Write a C# Sharp program that takes a character as input and check the input (lowercase) is a vowel, a digit, or any other symbol.</p>
            <p>@Html.ActionLink("See solution", "Index", "CharacterCheck")</p>
        </div>
        <div class="col-md-12 tasks">
            <h4>Task 10</h4>
            <p>Write a C# Sharp program that takes two numbers as input and returns true or false when both numbers are even or odd.</p>
            <p>@Html.ActionLink("See solution", "Index", "EvenOddNumbersCheck")</p>
        </div>
        <div class="col-md-12 tasks">
            <h4>Task 11</h4>
            <p>Write a C# Sharp program that takes a decimal number as input and displays its equivalent in binary form.</p>
            <p>@Html.ActionLink("See solution", "Index", "DecimalToBinaryConvert")</p>
        </div>      
    </div>
</div>